import 'package:grid_reconciler/grid_reconciler.dart';
import 'package:test/test.dart';

/// Parity suite for the Go `time.ParseDuration` / `Duration.String()` port.
///
/// Every expectation below is **Go ground truth**, generated by running the
/// listed inputs through go1.26 `time.ParseDuration`/`String()` (the same
/// stdlib gc 's pinned gascity build uses for `EncodeDuration` /
/// `DecodeDuration`, metadata.go:159-174) — not derived from this port.
void main() {
  group('GoDuration.parse — Go ground truth', () {
    const cases = <String, int>{
      // input -> nanoseconds (go run: time.ParseDuration)
      '5m': 300000000000,
      '5m0s': 300000000000,
      '1h2m3s': 3723000000000,
      '300ms': 300000000,
      '1.5h': 5400000000000,
      '2h45m': 9900000000000,
      '-1m30s': -90000000000,
      '1µs': 1000,
      '1us': 1000,
      '1μs': 1000, // greek mu
      '.5s': 500000000,
      '0': 0,
      '-0': 0,
      '+0': 0,
      '+5s': 5000000000,
      '1.5h30m': 7200000000000, // multi-component with fraction
      '90s': 90000000000,
      '1h': 3600000000000,
      '60s': 60000000000,
      '3600s': 3600000000000,
      '1.5µs': 1500,
      '1500ns': 1500,
      '100ns': 100,
      '0.000001s': 1000,
      '0.5us': 500,
      '1m': 60000000000,
      '1.000000001s': 1000000001,
      '2540400h10m10.000000000s': 9145440610000000000,
      // Fraction-overflow boundary class (go1.26.4 leadingFraction,
      // time/format.go:1577-1603) — adversarial ≥19-fractional-digit
      // inputs; every expectation go-run-verified 2026-06-12:
      '0.9223372036854775807s': 922337203, // last digit commits (2⁶³−1)
      '0.9223372036854775808s': 922337203, // exactly 2⁶³ — deviation class
      '0.9223372036854775809s': 922337203, // 2⁶³+1 — Go freezes too
      '1.9223372036854775808s': 1922337203, // with a leading integer part
      '0.92233720368547758089s': 922337203, // frozen scale: later digits inert
      '0.92233720368547758079s': 922337203,
      '0.99999999999999999999s': 1000000000, // frozen 18-nines fraction ≈ 1s
      '0.9223372036854775808h': 3320413933267, // exact-2⁶³ against unit h
      '0.184467440737095516161s': 184467440,
    };

    for (final entry in cases.entries) {
      test('parse "${entry.key}" -> ${entry.value} ns', () {
        expect(GoDuration.parse(entry.key), GoDuration(entry.value));
      });
    }

    const invalid = <String>[
      '',
      '5',
      's',
      '1d',
      '1 h',
      '.s',
      '-.s',
      '..5s',
      '1.2.3s',
      '1hh',
      '1h ',
      ' 1h',
      '1H',
    ];
    for (final input in invalid) {
      test('parse "$input" fails (Go errors)', () {
        expect(GoDuration.parse(input), isNull);
      });
    }
  });

  group('GoDuration.encode — Go Duration.String() ground truth', () {
    const cases = <int, String>{
      0: '0s',
      1: '1ns',
      999: '999ns',
      1000: '1µs',
      1500: '1.5µs',
      999999: '999.999µs',
      1000000: '1ms',
      1500000: '1.5ms',
      999999999: '999.999999ms',
      1000000000: '1s',
      1000000001: '1.000000001s',
      60000000000: '1m0s',
      90500000000: '1m30.5s',
      300000000000: '5m0s', // the default gate timeout as gc writes it
      3600000000000: '1h0m0s',
      3661000000000: '1h1m1s',
      -90000000000: '-1m30s',
      9223372036854775807: '2562047h47m16.854775807s',
      -9223372036854775808: '-2562047h47m16.854775808s',
    };

    for (final entry in cases.entries) {
      test('encode(${entry.key}) -> "${entry.value}"', () {
        expect(GoDuration(entry.key).encode(), entry.value);
      });
    }
  });

  group('round trips', () {
    test('encode(parse(s)) is stable for every gc-writable encoding', () {
      // Strings already in canonical Go String() form re-encode identically.
      for (final canonical in [
        '0s',
        '300ms',
        '1.5µs',
        '5m0s',
        '1h0m0s',
        '-1m30s',
        '1m30.5s',
      ]) {
        final parsed = GoDuration.parse(canonical);
        expect(parsed, isNotNull, reason: canonical);
        expect(parsed!.encode(), canonical);
      }
    });
  });

  group('bridges', () {
    test('toDuration truncates to microseconds toward zero', () {
      expect(
        const GoDuration(1500).toDuration(),
        const Duration(microseconds: 1),
      );
      expect(
        const GoDuration(-1500).toDuration(),
        const Duration(microseconds: -1),
      );
    });

    test('inMilliseconds matches Go Milliseconds() truncation', () {
      expect(const GoDuration(1999999).inMilliseconds, 1);
      expect(const GoDuration(-1999999).inMilliseconds, -1);
    });
  });
}
